#-------------------------------------------------------------------------------
# Daemon: Daemonize
#-------------------------------------------------------------------------------
daemonize = yes

#-------------------------------------------------------------------------------
# Daemon: Idle
#-------------------------------------------------------------------------------
exit-idle-time = -1
