#-------------------------------------------------------------------------------
# Anchor:
#-------------------------------------------------------------------------------
anchor=bottom-right

#-------------------------------------------------------------------------------
# Body:
#-------------------------------------------------------------------------------
body-font=interface
body-format=%b

#-------------------------------------------------------------------------------
# Default timeout:
#-------------------------------------------------------------------------------
default-timeout=10

#-------------------------------------------------------------------------------
# Edge margin:
#-------------------------------------------------------------------------------
edge-margin-horizontal=8
edge-margin-vertical=8

#-------------------------------------------------------------------------------
# Max icon size:
#-------------------------------------------------------------------------------
max-icon-size=32

#-------------------------------------------------------------------------------
# Max width:
#-------------------------------------------------------------------------------
max-width=320

#-------------------------------------------------------------------------------
# Min width:
#-------------------------------------------------------------------------------
min-width=320

#-------------------------------------------------------------------------------
# Notification margin:
#-------------------------------------------------------------------------------
notification-margin=8

#-------------------------------------------------------------------------------
# Padding:
#-------------------------------------------------------------------------------
padding-horizontal=12
padding-vertical=12

#-------------------------------------------------------------------------------
# Stacking order:
#-------------------------------------------------------------------------------
stacking-order=top-down

#-------------------------------------------------------------------------------
# Summary:
#-------------------------------------------------------------------------------
summary-font=interface
summary-format=%s\n

#-------------------------------------------------------------------------------
# Title:
#-------------------------------------------------------------------------------
title-font=interface
title-format=%a

#-------------------------------------------------------------------------------
# Low:
#-------------------------------------------------------------------------------
[low]
background=141933ff
body-color=6677ccff
border-color=323f7fff
summary-color=6677ccff
title-color=323f7fff

#-------------------------------------------------------------------------------
# Normal:
#-------------------------------------------------------------------------------
[normal]
background=1e4c3dff
body-color=72e5bfff
border-color=3d997aff
summary-color=72e5bfff
title-color=3d997aff

#-------------------------------------------------------------------------------
# Critical:
#-------------------------------------------------------------------------------
[critical]
background=662832ff
body-color=ff7f94ff
border-color=b24759ff
summary-color=ff7f94ff
title-color=b24759ff
