#-------------------------------------------------------------------------------
# Anchor:
#-------------------------------------------------------------------------------
anchor=bottom-right

#-------------------------------------------------------------------------------
# Body:
#-------------------------------------------------------------------------------
body-font=interface
body-format=%b

#-------------------------------------------------------------------------------
# Default timeout:
#-------------------------------------------------------------------------------
default-timeout=10

#-------------------------------------------------------------------------------
# Edge margin:
#-------------------------------------------------------------------------------
edge-margin-horizontal=8
edge-margin-vertical=8

#-------------------------------------------------------------------------------
# Max icon size:
#-------------------------------------------------------------------------------
max-icon-size=32

#-------------------------------------------------------------------------------
# Max width:
#-------------------------------------------------------------------------------
max-width=320

#-------------------------------------------------------------------------------
# Min width:
#-------------------------------------------------------------------------------
min-width=320

#-------------------------------------------------------------------------------
# Notification margin:
#-------------------------------------------------------------------------------
notification-margin=8

#-------------------------------------------------------------------------------
# Padding:
#-------------------------------------------------------------------------------
padding-horizontal=12
padding-vertical=12

#-------------------------------------------------------------------------------
# Stacking order:
#-------------------------------------------------------------------------------
stacking-order=top-down

#-------------------------------------------------------------------------------
# Summary:
#-------------------------------------------------------------------------------
summary-font=interface
summary-format=%s\n

#-------------------------------------------------------------------------------
# Title:
#-------------------------------------------------------------------------------
title-font=interface
title-format=%a

#-------------------------------------------------------------------------------
# Low:
#-------------------------------------------------------------------------------
[low]
background=222222ff
body-color=888888ff
border-color=555555ff
summary-color=888888ff
title-color=888888ff

#-------------------------------------------------------------------------------
# Normal:
#-------------------------------------------------------------------------------
[normal]
background=335588ff
body-color=99bbeeff
border-color=6688bbff
summary-color=99bbeeff
title-color=99bbeeff

#-------------------------------------------------------------------------------
# Critical:
#-------------------------------------------------------------------------------
[critical]
background=883355ff
body-color=ee99bbff
border-color=bb6688ff
summary-color=ee99bbff
title-color=ee99bbff
