#!/bin/bash

function user_prepare_directory
{
    git clone "https://github.com/jjura/dotfiles"

    for directory in   \
        ".config"      \
        ".local/bin"   \
        ".local/opt"   \
        ".local/share" \
        ".local/state"
    do
        mkdir --parents "$mountpoint/home/$username/$directory"
    done

    cp --recursive "dotfiles/home/." "$mountpoint/home/$username"
}

function user_prepare_ownership
{
    chown --recursive "$username":"$username" "/home/$username"
}

function user_prepare_fonts
{
    local-package "/home/$username/fonts" \
        "fonts-noto-color-emoji"          \
        "fonts-terminus-otb"

    cp --recursive                              \
        "/home/$username/fonts/usr/share/fonts" \
        "/home/$username/.local/share/fonts"

    rm --recursive "/home/$username/fonts"
}

function user_prepare_icons
{
    local-package "/home/$username/icons" "adwaita-icon-theme"

    cp --recursive                              \
        "/home/$username/icons/usr/share/icons" \
        "/home/$username/.local/share/icons"

    rm --recursive "/home/$username/icons"
}

function user_prepare_mime
{
    local-package "/home/$username/mime" "shared-mime-info"

    cp --recursive                            \
        "/home/$username/mime/usr/share/mime" \
        "/home/$username/.local/share/mime"

    ln --symbolic                   \
        "/home/$username/mime/mime" \
        "/home/$username/mime/update-mime-database"

    "/home/$username/mime/update-mime-database" \
        "/home/$username/.local/share/mime"

    rm --recursive "/home/$username/mime"
}

function user_prepare_schemas
{
    local-package "/home/$username/schemas" \
        "gsettings-desktop-schemas"         \
        "libgtk-3-common"

    cp --recursive                                   \
        "/home/$username/schemas/usr/share/glib-2.0" \
        "/home/$username/.local/share/glib-2.0"

    "/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas" \
        "/home/$username/.local/share/glib-2.0/schemas"

    rm --recursive "/home/$username/schemas"
}

function user_prepare_alsa
{
    local-package "/home/$username/.local/opt/alsa-utils" "alsa-utils"

    ln --symbolic                                          \
        "/home/$username/.local/opt/alsa-utils/alsa-utils" \
        "/home/$username/.local/bin/amixer"
}

function user_prepare_ddcutil
{
    local-package "/home/$username/.local/opt/ddcutil" "ddcutil"

    ln --symbolic                                    \
        "/home/$username/.local/opt/ddcutil/ddcutil" \
        "/home/$username/.local/bin/ddcutil"
}

function user_prepare_firefox
{
    local-package "/home/$username/.local/opt/firefox-esr" \
        "firefox-esr"                                      \
        "libavcodec61"

    ln --symbolic                                            \
        "/home/$username/.local/opt/firefox-esr/firefox-esr" \
        "/home/$username/.local/bin/firefox-esr"

    firefox-esr -CreateProfile "$username /home/$username/.config/firefox-esr"
}

function user_prepare_foot
{
    local-package "/home/$username/.local/opt/foot" "foot"

    ln --symbolic                              \
        "/home/$username/.local/opt/foot/foot" \
        "/home/$username/.local/bin/foot"
}

function user_prepare_imv
{
    local-package "/home/$username/.local/opt/imv" "imv"

    ln --symbolic                            \
        "/home/$username/.local/opt/imv/imv" \
        "/home/$username/.local/bin/imv"
}

function user_prepare_lf
{
    local-package "/home/$username/.local/opt/lf" "lf"

    ln --symbolic                          \
        "/home/$username/.local/opt/lf/lf" \
        "/home/$username/.local/bin/lf"
}

function user_prepare_libglib
{
    local-package "/home/$username/.local/opt/libglib2.0-bin" "libglib2.0-bin"

    ln --symbolic                                                  \
        "/home/$username/.local/opt/libglib2.0-bin/libglib2.0-bin" \
        "/home/$username/.local/bin/gsettings"

    for section in "document-font-name" "font-name" "monospace-font-name"
    do
        gsettings set org.gnome.desktop.interface "$section" "Terminus 9"
    done

    for section in "cursor-theme" "gtk-theme" "icon-theme"
    do
        gsettings set org.gnome.desktop.interface "$section" "Adwaita"
    done
}

function user_prepare_neovim
{
    local-package "/home/$username/.local/opt/neovim" "neovim"

    ln --symbolic                                  \
        "/home/$username/.local/opt/neovim/neovim" \
        "/home/$username/.local/bin/nvim"
}

function user_prepare_sway
{
    local-package "/home/$username/.local/opt/sway" "sway"

    ln --symbolic                              \
        "/home/$username/.local/opt/sway/sway" \
        "/home/$username/.local/bin/sway"

    ln --symbolic                              \
        "/home/$username/.local/opt/sway/sway" \
        "/home/$username/.local/bin/swaymsg"

    ln --symbolic                              \
        "/home/$username/.local/opt/sway/sway" \
        "/home/$username/.local/bin/swaynag"
}

function user_prepare_swayidle
{
    local-package "/home/$username/.local/opt/swayidle" "swayidle"

    ln --symbolic                                      \
        "/home/$username/.local/opt/swayidle/swayidle" \
        "/home/$username/.local/bin/swayidle"
}

function user_prepare_tofi
{
    local-package "/home/$username/.local/opt/tofi" "tofi"

    ln --symbolic                              \
        "/home/$username/.local/opt/tofi/tofi" \
        "/home/$username/.local/bin/tofi"
}

function user_prepare_xdg
{
    local-package "/home/$username/.local/opt/xdg-utils" "xdg-utils"

    ln --symbolic                                        \
        "/home/$username/.local/opt/xdg-utils/xdg-utils" \
        "/home/$username/.local/bin/xdg-mime"

    ln --symbolic                                        \
        "/home/$username/.local/opt/xdg-utils/xdg-utils" \
        "/home/$username/.local/bin/xdg-open"
}

function user_prepare_xwayland
{
    local-package "/home/$username/.local/opt/xwayland" "xwayland"
}
