#!/bin/bash

function device_configure_partition
{
    parted "$device" --script                     \
        mklabel gpt                               \
        mkpart "'boot partition'" fat32 1MiB 1GiB \
        mkpart "'root partition'" ext4 1GiB 11GiB \
        mkpart "'home partition'" ext4 11GiB 100% \
        set 1 esp on
}

function device_configure_filesystem
{
    mkfs.fat  -F32 "${device}p1"
    mkfs.ext4 -F   "${device}p2"
    mkfs.ext4 -F   "${device}p3"
}

function device_configure_mountpoint
{
    mount --types ext4 "${device}p2" "$mountpoint"

    mkdir                  \
        "$mountpoint/boot" \
        "$mountpoint/home"

    mount --types ext4 "${device}p3" "$mountpoint/home"
    mount --types vfat "${device}p1" "$mountpoint/boot"
}

function device_configure_uuid
{
    for uuid in "/dev/disk/by-uuid/"*
    do
        if [ "$(readlink --canonicalize "$uuid")" = "$1" ]
        then
            basename "$uuid"
        fi
    done
}
