#!/bin/bash

function user_configure_dotfiles
{
    git clone "https://github.com/jjura/dotfiles" \
        --recurse-submodules                      \
        --branch "debian" "/tmp/dotfiles"

    cp --recursive "/tmp/dotfiles/home/." "$mountpoint/home/$username"
}

function user_configure_alacritty
{
    local-package "/home/$username/.local/opt/alacritty" \
        "alacritty"                                      \
        "libwayland-egl1"

    ln --symbolic                                        \
        "/home/$username/.local/opt/alacritty/alacritty" \
        "/home/$username/.local/bin/alacritty"
}

function user_configure_firefox
{
    local-package "/home/$username/.local/opt/firefox-esr" \
        "firefox-esr"                                      \
        "libavcodec59"                                     \
        "libgl1"                                           \
        "libpulse0"

    ln --symbolic                                            \
        "/home/$username/.local/opt/firefox-esr/firefox-esr" \
        "/home/$username/.local/bin/firefox-esr"
}

function user_configure_fonts
{
    local-package "/home/$username/fonts" \
        "fonts-dejavu-core"               \
        "fonts-noto-color-emoji"          \
        "fonts-terminus-otb"

    cp --recursive                              \
        "/home/$username/fonts/usr/share/fonts" \
        "/home/$username/.local/share/fonts"

    rm --recursive "/home/$username/fonts"
}

function user_configure_gsettings
{
    local-package "/home/$username/.local/opt/libglib2.0-bin" "libglib2.0-bin"

    ln --symbolic                                                  \
        "/home/$username/.local/opt/libglib2.0-bin/libglib2.0-bin" \
        "/home/$username/.local/bin/gsettings"
}

function user_configure_icons
{
    local-package "/home/$username/icons" "adwaita-icon-theme"

    cp --recursive                              \
        "/home/$username/icons/usr/share/icons" \
        "/home/$username/.local/share/icons"

    rm --recursive "/home/$username/icons"
}

function user_configure_mime
{
    local-package "/home/$username/mime" "shared-mime-info"

    cp --recursive                            \
        "/home/$username/mime/usr/share/mime" \
        "/home/$username/.local/share/mime"

    ln --symbolic                   \
        "/home/$username/mime/mime" \
        "/home/$username/mime/update-mime-database"

    "/home/$username/mime/update-mime-database" \
        "/home/$username/.local/share/mime"

    rm --recursive "/home/$username/mime"
}


function user_configure_neovim
{
    local-package "/home/$username/.local/opt/neovim" "neovim"

    ln --symbolic                                  \
        "/home/$username/.local/opt/neovim/neovim" \
        "/home/$username/.local/bin/nvim"
}

function user_configure_playerctl
{
    local-package "/home/$username/.local/opt/playerctl" "playerctl"

    ln --symbolic                                        \
        "/home/$username/.local/opt/playerctl/playerctl" \
        "/home/$username/.local/bin/playerctl"
}

function user_configure_pulseaudio
{
    local-package "/home/$username/.local/opt/pulseaudio" \
        "pulseaudio"                                      \
        "pulseaudio-module-bluetooth"

    ln --symbolic                                          \
        "/home/$username/.local/opt/pulseaudio/pulseaudio" \
        "/home/$username/.local/bin/pulseaudio"

    ln --symbolic                                          \
        "/home/$username/.local/opt/pulseaudio/pulseaudio" \
        "/home/$username/.local/bin/pactl"
}

function user_configure_schemas
{
    local-package "/home/$username/schemas" \
        "gsettings-desktop-schemas"         \
        "libgtk-3-common"

    cp --recursive                                   \
        "/home/$username/schemas/usr/share/glib-2.0" \
        "/home/$username/.local/share/glib-2.0"

    "/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas" \
        "/home/$username/.local/share/glib-2.0/schemas"

    rm --recursive "/home/$username/schemas"
}

function user_configure_sway
{
    local-package "/home/$username/.local/opt/sway" "sway" "libglib2.0-bin"

    ln --symbolic                              \
        "/home/$username/.local/opt/sway/sway" \
        "/home/$username/.local/bin/sway"

    ln --symbolic                              \
        "/home/$username/.local/opt/sway/sway" \
        "/home/$username/.local/bin/swaymsg"

    ln --symbolic                              \
        "/home/$username/.local/opt/sway/sway" \
        "/home/$username/.local/bin/swaynag"
}

function user_configure_swaylock
{
    local-package "/home/$username/.local/opt/swaylock" "swaylock"

    ln --symbolic                                      \
        "/home/$username/.local/opt/swaylock/swaylock" \
        "/home/$username/.local/bin/swaylock"
}

function user_configure_tofi
{
    local-package "/home/$username/.local/opt/tofi" "tofi"

    ln --symbolic                              \
        "/home/$username/.local/opt/tofi/tofi" \
        "/home/$username/.local/bin/tofi-drun"
}

function user_configure_xwayland
{
    local-package "/home/$username/.local/opt/xwayland" "xwayland"
}
